config/routes.rb
Indausfair::Application.routes.draw do

  get "mission/index"
  match "mission" => "mission/index"

  resources :enquiries


  resources :sponsors


  	get "admin/index"
    match "admin" => "admin/index"

    get "sponsors/index"
    match "sponsors" => "sponsors/index"

  	get "gallery/index"
    match "gallery" => "gallery#index"

    get "home/index"
    match "home" => "home#index"
    
   	get "home/privacy"
  	match "privacy" => "home#privacy"

  	get "home/contact"
  	match "contact" => "home#contact"

  	get "home/about"
  	match "about" => "home#about"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.json
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render json: @sponsor, status: :created, location: @sponsor }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.json
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= simple_form_for(@sponsor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h3>Editing sponsor</h3>

<%= render 'form' %>

<%= link_to 'Show', @sponsor %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/index.html.erb
<h3>Our Sponsors</h3>


  
    Rosehill Gardens
    <br>
    <a href="http://www.krivaan.com/"><img src="http://www.krivaan.com/wp-content/uploads/2012/07/Krivaan156x74.png" width="156" height="52" alt="Krivaan" /></a>
    <br>
    Floral Vibes
    <br>


<% @sponsors.each do |sponsor| %>
  <tr>
    <!--<td><%= link_to 'Show', sponsor %></td>-->
    <td><%= link_to 'Edit', edit_sponsor_path(sponsor) %></td>
    <td><%= link_to 'Destroy', sponsor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

<br />

<%= link_to 'New Sponsor', new_sponsor_path %>

app/views/sponsors/new.html.erb
<h3>New sponsor</h3>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>