config/routes.rb
Indausfair::Application.routes.draw do

  get "mission/index"
  match "mission" => "mission/index"

  resources :enquiries


  resources :sponsors


  	get "admin/index"
    match "admin" => "admin/index"

    get "sponsors/index"
    match "sponsors" => "sponsors/index"

  	get "gallery/index"
    match "gallery" => "gallery#index"

    get "home/index"
    match "home" => "home#index"
    
   	get "home/privacy"
  	match "privacy" => "home#privacy"

  	get "home/contact"
  	match "contact" => "home#contact"

  	get "home/about"
  	match "about" => "home#about"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  attr_accessible :email, :message, :name, :subject
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @enquiries }
    end
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
    @enquiry = Enquiry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @enquiry }
    end
  end

  # GET /enquiries/new
  # GET /enquiries/new.json
  def new
    @enquiry = Enquiry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enquiry }
    end
  end

  # GET /enquiries/1/edit
  def edit
    @enquiry = Enquiry.find(params[:id])
  end

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(params[:enquiry])

    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully created.' }
        format.json { render json: @enquiry, status: :created, location: @enquiry }
      else
        format.html { render action: "new" }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /enquiries/1
  # PUT /enquiries/1.json
  def update
    @enquiry = Enquiry.find(params[:id])

    respond_to do |format|
      if @enquiry.update_attributes(params[:enquiry])
        format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry = Enquiry.find(params[:id])
    @enquiry.destroy

    respond_to do |format|
      format.html { redirect_to enquiries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>

 
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :subject %>
    <%= f.input :message, :as => :text, :input_html => { :class => "span1", :rows => 3} %>
  
    <%= f.submit "Submit", :class => "btn btn-success", :style => "color:white;" %>
  
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<h1>Listing enquiries</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Subject</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enquiries.each do |enquiry| %>
  <tr>
    <td><%= enquiry.name %></td>
    <td><%= enquiry.email %></td>
    <td><%= enquiry.subject %></td>
    <td><%= enquiry.message %></td>
    <td><%= link_to 'Show', enquiry %></td>
    <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
    <td><%= link_to 'Destroy', enquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
			<h2><center>Contact us for Sponsorship and Tickets</center></h2>
<div class="container">
	<div class="row">
		<div class="span2">
			<%= render 'form' %>
<br>
<br>
	<%= link_to 'Back', enquiries_path %>
		</div>
	</div>

	<div class="pull-right">
		<div class="span6">
			<h4>Phone</h4>
			<h4>Email</h4>
		</div>
	</div>
</div>

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @enquiry.name %>
</p>

<p>
  <b>Email:</b>
  <%= @enquiry.email %>
</p>

<p>
  <b>Subject:</b>
  <%= @enquiry.subject %>
</p>

<p>
  <b>Message:</b>
  <%= @enquiry.message %>
</p>


<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>