config/routes.rb
Indausfair::Application.routes.draw do

  get "mission/index"
  match "mission" => "mission/index"

  resources :enquiries


  resources :sponsors


  	get "admin/index"
    match "admin" => "admin/index"

    get "sponsors/index"
    match "sponsors" => "sponsors/index"

  	get "gallery/index"
    match "gallery" => "gallery#index"

    get "home/index"
    match "home" => "home#index"
    
   	get "home/privacy"
  	match "privacy" => "home#privacy"

  	get "home/contact"
  	match "contact" => "home#contact"

  	get "home/about"
  	match "about" => "home#about"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_footer.html.erb
<!--<div class="footer">
	<hr>
	<div class="pull-left"><p>&copy; INDAUS ASSOC. 2013</p></div>     
	<div class="pull-right"><%= link_to 'Contact Us', contact_path %> &middot; <%= link_to 'Privacy', privacy_path %> &middot; <%= link_to 'About Us', about_path %> &middot; </div>
	<br>
</div>-->

<p "align" class="pull-right">
	<a href="#">Back to top</a>
</p>

<p "align">
	&copy; 2013 INDAUS Inc. 
	&nbsp;

	<a href="/privacy">Privacy</a> &nbsp;

	<a href="/enquiries/new">Contact</a> &nbsp;

	<!--<a href="https://twitter.com/SydneyDevCamp" target="_blank">
		<i class="icon-twitter"></i>
		 @SydneyDevCamp
	</a> &nbsp;-->

	<a href="https://www.facebook.com/INDAUS.NSW" target="_blank">
		<i class="icon-facebook"></i>
		 Facebook
	</a> &nbsp;

	<!--<a href="https://plus.google.com/114736942787903829890" rel="publisher" target="_blank">
		<i class="icon-google-plus"></i>
		 Google+ 
	</a> &nbsp;-->
	<br>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!--<div class="navbar navbar-inverse">
    <div class="navbar-inner">
    <a class="brand" href="#">Title</a>
    <ul class="nav">
       <li class="dropdown">
        <a class="dropdown-toggle"
          data-toggle="dropdown"
          href="#">
          Dropdown
          <b class="caret"></b>
        </a>
    <ul class="dropdown-menu">-->
          <!-- links -->
    <!--</ul>-->
    <!--<li class="active"><a href="#">Home</a></li>
    <li><a href="#">Link</a></li>
    <li><a href="#">Link</a></li>
    </ul>
    </div>
    </div>-->


<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <ul class="nav pull-left">
      <li>
        <a href="home">INDAUS Fair</a>
      </li>
    </ul>
    <ul class="nav pull-right">

       <li>
          <%= link_to "Contact",  new_enquiry_path %>
      </li>
      <li>
        <%= link_to "Gallery", gallery_path %>
      </li>
      <li>
        <%= link_to "Sponsors", sponsors_path %>
      </li>
      <li>
        <%= link_to "Mission", mission_index_path %>
      </li>
      <li><%= link_to 'Login', new_user_session_path %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
      
    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Admin', users_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
      <% end %>
    <% end %>
    </ul>
  </div>
</div>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "INDAUS Fair" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "INDAUS Fair" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <!--<nav class="navbar-inner">-->
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">

              <%= render 'layouts/messages' %>
              <%= yield %>

      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
          <footer>
            <%= render 'layouts/footer' %>
          </footer>
     
  </body>
</html>